name: 'Rythmixx 이슈 생성'
description: 'Rythmixx 관련 이슈를 생성합니다.'
labels: [order]
title: '이슈 이름을 작성해주세요'

body:
  - type: dropdown
    id: issueType
    attributes:
      label: '이슈 유형 (Issue Type)'
      description: '해당하는 이슈 유형을 선택해주세요.'
      options:
        - '🛠️ refactor: 성능 최적화, 코드 리팩토링, 중복 코드 제거 등의 작업을 포함합니다.'
        - '🐞 bug: 기존 코드에서 발생한 오류나 문제를 수정합니다.'
        - '✨ feat: 새로운 기능이나 주요 변경 사항을 추가합니다.'
        - '🛠️ fix: 사소한 오류, 오타, UI 깨짐과 같은 작은 문제를 수정합니다.'
        - '🧹 chore: 파일 삭제, 문서 추가, 의존성 업데이트, 환경 설정 변경 등의 작업을 포함합니다.'
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: '이슈 내용(Description)'
      description: '이슈에 대해서 간략히 설명해주세요'
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: '상세 내용(Details)'
      description: '이슈에 대해서 자세히 설명해주세요'
      value: |
        - About Details
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '체크리스트(Tasks)'
      description: '해당 이슈에 대해 필요한 작업 목록을 작성해주세요'
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true
